// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/client.service.proto

package com.ljzn.grpc.client;

public final class ClientService {
  private ClientService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JdSystem_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JdSystem_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JdSystem_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JdSystem_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JdSystem_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JdSystem_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JdSystem_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JdSystem_HeartbeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033client/client.service.proto\022\010JdSystem\032" +
      "\033client/client.message.proto\"N\n\014LoginReq" +
      "uest\022\'\n\006client\030\001 \001(\0132\027.JdSystem.ClientMe" +
      "ssage\022\025\n\rclient_secret\030\002 \001(\t\"@\n\rLoginRes" +
      "ponse\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\020\n\010" +
      "belongId\030\003 \001(\t\"\'\n\020HeartbeatRequest\022\023\n\013de" +
      "viceSeril\030\001 \001(\t\"E\n\021HeartbeatResponse\022\014\n\004" +
      "code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\021\n\ttimeStamp" +
      "\030\003 \001(\0032\227\001\n\021ClientAuthService\022:\n\005Login\022\026." +
      "JdSystem.LoginRequest\032\027.JdSystem.LoginRe" +
      "sponse\"\000\022F\n\tHeartBeat\022\032.JdSystem.Heartbe" +
      "atRequest\032\033.JdSystem.HeartbeatResponse\"\000" +
      "B!\n\024com.ljzn.grpc.clientP\001\242\002\006CLIENTb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ljzn.grpc.client.ClientMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_JdSystem_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JdSystem_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JdSystem_LoginRequest_descriptor,
        new java.lang.String[] { "Client", "ClientSecret", });
    internal_static_JdSystem_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_JdSystem_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JdSystem_LoginResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "BelongId", });
    internal_static_JdSystem_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_JdSystem_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JdSystem_HeartbeatRequest_descriptor,
        new java.lang.String[] { "DeviceSeril", });
    internal_static_JdSystem_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_JdSystem_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JdSystem_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "TimeStamp", });
    com.ljzn.grpc.client.ClientMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
