// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/client.service.proto

package com.ljzn.grpc.client;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JdSystem.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.JdSystem.ClientMessage client = 1;</code>
   */
  boolean hasClient();
  /**
   * <code>.JdSystem.ClientMessage client = 1;</code>
   */
  com.ljzn.grpc.client.ClientMessage getClient();
  /**
   * <code>.JdSystem.ClientMessage client = 1;</code>
   */
  com.ljzn.grpc.client.ClientMessageOrBuilder getClientOrBuilder();

  /**
   * <pre>
   *设备编号的加盐MD5值，盐值由客户端与服务器端约定
   * </pre>
   *
   * <code>string client_secret = 2;</code>
   */
  java.lang.String getClientSecret();
  /**
   * <pre>
   *设备编号的加盐MD5值，盐值由客户端与服务器端约定
   * </pre>
   *
   * <code>string client_secret = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientSecretBytes();
}
