// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.message.proto

package com.ljzn.grpc.personinfo;

public final class PersoninfoMessageOuterClass {
  private PersoninfoMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JdSystem_PersoninfoMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JdSystem_PersoninfoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#personinfo/personinfo.message.proto\022\010J" +
      "dSystem\"\220\001\n\021PersoninfoMessage\022\016\n\006cardId\030" +
      "\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\024\n\014photoFeature\030\004 \003(" +
      "\002\022\027\n\017photoFeatureLen\030\005 \001(\003\022\r\n\005photo\030\006 \001(" +
      "\014\022\017\n\007version\030\007 \001(\003\022\016\n\006action\030\010 \001(\005B)\n\030co" +
      "m.ljzn.grpc.personinfoP\001\242\002\nPERSONINFOb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_JdSystem_PersoninfoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JdSystem_PersoninfoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JdSystem_PersoninfoMessage_descriptor,
        new java.lang.String[] { "CardId", "Name", "PhotoFeature", "PhotoFeatureLen", "Photo", "Version", "Action", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
