// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.message.proto

package com.ljzn.grpc.personinfo;

/**
 * Protobuf enum {@code JdSystem.PersonType}
 */
public enum PersonType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *学习人员
   * </pre>
   *
   * <code>Learner = 0;</code>
   */
  Learner(0),
  /**
   * <pre>
   *领导
   * </pre>
   *
   * <code>Leader = 1;</code>
   */
  Leader(1),
  /**
   * <pre>
   *工作人员
   * </pre>
   *
   * <code>Worker = 2;</code>
   */
  Worker(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *学习人员
   * </pre>
   *
   * <code>Learner = 0;</code>
   */
  public static final int Learner_VALUE = 0;
  /**
   * <pre>
   *领导
   * </pre>
   *
   * <code>Leader = 1;</code>
   */
  public static final int Leader_VALUE = 1;
  /**
   * <pre>
   *工作人员
   * </pre>
   *
   * <code>Worker = 2;</code>
   */
  public static final int Worker_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PersonType valueOf(int value) {
    return forNumber(value);
  }

  public static PersonType forNumber(int value) {
    switch (value) {
      case 0: return Learner;
      case 1: return Leader;
      case 2: return Worker;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PersonType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PersonType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PersonType>() {
          public PersonType findValueByNumber(int number) {
            return PersonType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final PersonType[] VALUES = values();

  public static PersonType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PersonType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:JdSystem.PersonType)
}

