// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.service.proto

package com.ljzn.grpc.personinfo;

public interface PersoninfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JdSystem.PersoninfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *软件启动时上传的version值是0,然后服务端会返回全部数据 
   * </pre>
   *
   * <code>int64 version = 1;</code>
   */
  long getVersion();

  /**
   * <pre>
   *false不需要 true 须要
   * </pre>
   *
   * <code>bool needPhoto = 2;</code>
   */
  boolean getNeedPhoto();

  /**
   * <code>string deviceSeril = 3;</code>
   */
  java.lang.String getDeviceSeril();
  /**
   * <code>string deviceSeril = 3;</code>
   */
  com.google.protobuf.ByteString
      getDeviceSerilBytes();
}
