// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.service.proto

package com.ljzn.grpc.personinfo;

public final class PersoninfoService {
  private PersoninfoService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JdSystem_PersoninfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JdSystem_PersoninfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JdSystem_PersoninfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JdSystem_PersoninfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#personinfo/personinfo.service.proto\022\010J" +
      "dSystem\032#personinfo/personinfo.message.p" +
      "roto\"L\n\021PersoninfoRequest\022\017\n\007version\030\001 \001" +
      "(\003\022\021\n\tneedPhoto\030\002 \001(\010\022\023\n\013deviceSeril\030\003 \001" +
      "(\t\"d\n\022PersoninfoResponse\022\014\n\004code\030\001 \001(\005\022\017" +
      "\n\007message\030\002 \001(\t\022/\n\npersonInfo\030\003 \003(\0132\033.Jd" +
      "System.PersoninfoMessage2e\n\025PersonInfoAu" +
      "thService\022L\n\rGetPersonInfo\022\033.JdSystem.Pe" +
      "rsoninfoRequest\032\034.JdSystem.PersoninfoRes" +
      "ponse\"\000B)\n\030com.ljzn.grpc.personinfoP\001\242\002\n" +
      "PERSONINFOb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_JdSystem_PersoninfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JdSystem_PersoninfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JdSystem_PersoninfoRequest_descriptor,
        new java.lang.String[] { "Version", "NeedPhoto", "DeviceSeril", });
    internal_static_JdSystem_PersoninfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_JdSystem_PersoninfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JdSystem_PersoninfoResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "PersonInfo", });
    com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
