server:
  port: 8080
grpc:
  server:
    port: 50051
spring:
  datasource:
    name: te
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://218.2.211.35:3306/yj_jd_api?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: jd_123
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  resources:
    static-locations: classpath:/static/,classpath:upload/images/
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis: 
  mapper-locations: classpath*:com/jian/dao/mapper/*.xml